### ISSUE TITLE
Make Operating System options optional when PVC is also selected

### ISSUE THREAD

**Issue by vatsalparekh** [masayag/foreman_kubevirt#29]
If a user is selecting a PVC, which might have the OS source, defining the Operating system options might would be conflicting or unnecessary, they should be made optional.

Somewhat related to #28

**Comment by shiramax** [comment]
We don't have an option in foreman to check if an operating system is installed on a PVC (and we also don't do it in foeman other compute resource), that's why the operating system is mandatory. 
I'm closing this issue, but if you think it's still relevant, you can file a bug to foreman

**Comment by vatsalparekh** [comment]
In the context of KubeVirt, if user is attaching a PVC, there's a flow of CDI where the PVC already has the OS, this issue is for making selecting the Operating System options optional if user already has OS installed and we don't need to do anything from Foreman side, just create a VM object and attach that PVC to it.
@masayag your thoughts?

**Comment by masayag** [comment]
@vatsalparekh foreman suggests using host-group to prepare a template of the installation in which you may define the the OS, arch and any other property.
If you're familiar with the OS installed on the image, you can prepare a host group with that definition once and reuse it for any installation.
I don't think foreman has a way to know what is installed on the disk at this step, since it relies on gather facts being executed on a latter step.
